name: Build and Lint
on: [push]

env:
  # Pretty cargo output!
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-D warnings"
  CARGO_BUILD_TARGET: wasm32-unknown-unknown

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build | Checkout
        uses: actions/checkout@v4

      - name: Build | Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Build | Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | rustfmt
        run: cargo fmt -- --check

      - name: Build | clippy
        run: cargo clippy --all-features

      - name: Build
        run: cargo build

