name: Build
on: [push]

env:
  # Pretty cargo output!
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-D warnings"
  CARGO_BUILD_TARGET: wasm32-unknown-unknown

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
