name: Deploy to Development

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development | Checkout
        uses: actions/checkout@v4

      - name: Deploy to Development | Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: canister_${{ github.sha }}
          path: wasm

      - name: Deploy to Development | Install dfx
        uses: dfinity/setup-dfx@main

      - name: Deploy to Development | Authenticate
        run: |
          echo ${{ secrets.CATALYZE_DEVELOPMENT }} | base64 --decode > catalyze_development.pem
          dfx identity import --storage-mode=plaintext catalyze_development catalyze_development.pem
          dfx identity use catalyze_development

      - name: Deploy to Development | Deploy
        run: dfx canister install canister --network development --wasm wasm/canister_${{ github.sha }}.wasm.gz --mode upgrade
