name: Build and Deploy to Development

on:
  push:
    branches: 
      - master

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: ${{ github.sha }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          lint: 'true'
          test: 'true'
          gzip: 'true'
          version: ${{ env.VERSION }}
          build_args: '--release'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canister_${{ env.VERSION }}
          path: wasm/canister_${{ env.VERSION }}.wasm.gz
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: canister_${{ env.VERSION }}
          path: wasm

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          identity: ${{ secrets.CATALYZE_DEVELOPMENT }}
          canister_name: canister
          network: development
          wasm_file: wasm/canister_${{ env.VERSION }}.wasm.gz
