name: Deploy to Development

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          lint: 'false'
          gzip: 'true'
          build_args: '--release'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canister_${{ github.sha }}
          path: wasm/canister_${{ github.sha }}.wasm.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: canister_${{ github.sha }}
          path: wasm

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          identity: ${{ secrets.CATALYZE_DEVELOPMENT }}
          canister_name: canister
          network: development
          wasm_file: wasm/canister_${{ github.sha }}.wasm.gz
