name: Build and Deploy to Staging

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: ${{ github.ref_name }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          lint: 'false'
          gzip: 'true'
          version: ${{ env.VERSION }}
          build_args: '--release'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: canister_${{ env.VERSION }}
          path: wasm/canister_${{ env.VERSION }}.wasm.gz
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: canister_${{ env.VERSION }}
          path: wasm

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          # use development network and secrets just for testing, replace it with the staging
          identity: ${{ secrets.CATALYZE_DEVELOPMENT }}
          canister_name: canister
          network: development
          wasm_file: wasm/canister_${{ env.VERSION }}.wasm.gz
